import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import FFooter from "@/components/home/future/Footer";
import PFooter from "@/components/home/past/Footer";
import Navbar from "@/components/common/Navbar";
import SessionProvider from "@/components/common/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const gg = false;
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        {
          gg?<FFooter/>:<PFooter/>
        }
        <SessionProvider />
      </body>
    </html>
  );
}
